import json
import os
from pydantic import BaseModel, Field
from langchain_core.messages import HumanMessage
from app.services.state import GraphState
from app.services.utils import encode_image, get_gemini_llm

# --- MOCK DATABASE (Connected to your synthetic metadata!) ---
def load_mock_db():
    db = {}
    # Point to the metadata.json file generated by your scripts
    base_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "Assignment2_datagen_scripts", "scripts", "scripts", "dataset")
    metadata_path = os.path.join(base_dir, "metadata.json")
    
    try:
        with open(metadata_path, "r") as f:
            data = json.load(f)
            # Add every generated policy number into our "Database"
            for item in data:
                if "policy_number" in item:
                    # Store both the original and a normalized version for fuzzy matching
                    raw = item["policy_number"]
                    db[raw.strip().upper()] = "VERIFIED_ACTIVE"
                    # Also store a stripped version (no dashes/spaces) for fuzzy fallback
                    normalized = raw.strip().upper().replace("-", "").replace(" ", "")
                    db[normalized] = "VERIFIED_ACTIVE"
    except Exception as e:
        print("Warning: Could not load metadata.json for mock DB.", e)
        
    return db

# Load it once into memory when the server starts
MEMBER_DATABASE = load_mock_db()

def check_member_db(member_id: str) -> str:
    """Looks up the extracted Policy Number against the generated JSON database."""
    if not member_id or member_id.strip() == "":
        return "NOT_FOUND"
        
    # Check exact match first (case-insensitive)
    clean_id = member_id.strip().upper()
    if clean_id in MEMBER_DATABASE:
        return MEMBER_DATABASE[clean_id]
    
    # Fuzzy fallback: strip dashes and spaces, then check
    normalized = clean_id.replace("-", "").replace(" ", "")
    if normalized in MEMBER_DATABASE:
        return MEMBER_DATABASE[normalized]
        
    return "NOT_FOUND"

# Define exactly what we want from the ID card
class KYCData(BaseModel):
    name: str = Field(description="Full name on the ID")
    dob: str = Field(description="Date of birth")
    member_id: str = Field(description="Member ID or Policy Number")
    expiry_date: str = Field(description="Expiry date of the ID")
    is_expired: bool = Field(description="True if the expiry date is before today, False otherwise")
    tampering_detected: bool = Field(description="True if there are obvious signs of tampering. False if authentic.")

def kyc_node(state: GraphState) -> GraphState:
    print(f"--- KYC AGENT RUNNING for {state['case_id']} ---")
    
    base64_image = encode_image(state["file_path"])
    llm = get_gemini_llm()
    structured_llm = llm.with_structured_output(KYCData)
    
    prompt = """You are an expert fraud detection and KYC AI. 
Look at this ID Document. Extract the Name, DOB, Member ID, and Expiry Date. 
Check if the ID is expired (assume today's date is 2025-05-08).
Also, look very closely for signs of tampering (mismatched fonts, weird artifacts)."""
    
    message = HumanMessage(
        content=[
            {"type": "text", "text": prompt},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}},
        ]
    )
    
    try:
        response = structured_llm.invoke([message])
        kyc_dict = response.model_dump()
        
        # --- DATABASE VALIDATION STEP ---
        print(f"Validating Member ID {kyc_dict['member_id']} against database...")
        db_status = check_member_db(kyc_dict["member_id"])
        kyc_dict["database_status"] = db_status
        
        # Determine overall KYC Pass/Fail
        if kyc_dict["is_expired"] or kyc_dict["tampering_detected"] or db_status == "NOT_FOUND":
            kyc_dict["overall_pass"] = False
        else:
            kyc_dict["overall_pass"] = True
            
        state["kyc_result"] = kyc_dict
        print(f"Successfully extracted and validated KYC: {state['kyc_result']}")
        
    except Exception as e:
        print(f"KYC failed: {e}")
        state["kyc_result"] = {"error": "Failed to parse ID", "overall_pass": False}
        
    return state
